version: "3.5"
services:
  app:
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"  
    volumes:
      - ~/Documents/Github/science-editor-microservices/data:/app
      - ./:/app